# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

# Publications

# Main top-level menu for publications

[[main]]
  name = "Selected publications"
  url = "/publications"
  identifier="publications"
  weight = 20

 # Sub-headings

[[main]]
  name = "All"
  url = "/publications/"
  weight = 10
  parent = "publications"

[[main]]
  name = "Journal"
  url = "/publications/#journal"
  weight = 20
  parent = "publications"


[[main]]
  name = "Conference"
  url = "/publications/#conference"
  weight = 30
  parent = "publications"

[[main]]
  name = "Workshop"
  url = "/publications/#workshop"
  weight = 40
  parent = "publications"

[[main]]
  name = "Technical report"
  url = "/publications/#techreport"
  weight = 50
  parent = "publications"

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 20

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
 name = "CV"
 url = "files/DMRosen_CV.pdf"
 weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

